spring:
  application:
    name: mufengapi-backendV2
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8848:3306/mufengapi
    username: root
    password: Asdf0823
  mail:
    host: smtp.qq.com
    username: 123@qq.com
    password: 321
    default-encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #路径匹配策略
  # session 失效时间（分钟）
  session:
    timeout: 86400 # 单位为秒，即24小时。如果应用在一段时间内没有活动，那么用户的Session将在24小时后过期，需要重新登录。
    store-type: redis # 设置为none，表示不进行Session的持久化存储 或者使用Redis作为Session存储介质可以提高Session的可靠性和可扩展性，适用于生产环境或需要分布式部署的场景
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0


server:
  port: 8001
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: none
        secure: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 是否开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

dubbo:
  application:
    name: mufengapi-backendV2
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848