server:
  port: 8090
spring:
  cloud:
    main:
      web-application-type: reactive
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: mufengapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://10.206.25.10:8091