server:
  port: 8002
spring:
  application:
    name: mufengapi-gatewayV2
  cloud:
    gateway:
      routes:
        - id: api_route2
          uri: https://api.btstu.cn
          predicates:
            - Path=/api/interface/getRandomImage
          filters:
            - SetPath=/sjbz/api.php
        - id: api_route3
          uri: https://v2.alapi.cn
          predicates:
            - Path=/api/interface/getRandomWords
          filters:
            - SetPath=/api/soul
        - id: api_route4
          uri: https://api.oioweb.cn
          predicates:
            - Path=/api/interface/getQueryICP
          filters:
            - SetPath=/api/site/icp
        - id: api_route6
          uri: https://api.btstu.cn
          predicates:
            - Path=/api/interface/getQueryDomain
          filters:
            - SetPath=/dmreg/api.php
        - id: api_route7
          uri: https://api.oioweb.cn
          predicates:
            - Path=/api/interface/getQueryHistory
          filters:
            - SetPath=/api/common/history
        - id: api_route8
          uri: https://api.oioweb.cn
          predicates:
            - Path=/api/interface/getRandomAvatar
          filters:
            - SetPath=/api/picture/miyoushe_avatar
        - id: api_route9
          uri: https://api.oioweb.cn
          predicates:
            - Path=/api/interface/getRandomCXK
          filters:
            - SetPath=/api/picture/SogouServlet
        - id: api_route10
          uri: https://api.oioweb.cn
          predicates:
            - Path=/api/interface/getQueryRC
          filters:
            - SetPath=/api/common/rubbish


dubbo:
  application:
    name: mufengapi-gatewayV2
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8849