server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:7529
          predicates:
            - Path=/api/name/user
        - id: api_route2
          uri: https://api.btstu.cn
          predicates:
            - Path=/api/interface/getRandomImage
          filters:
            - SetPath=/sjbz/api.php
        - id: api_route3
          uri: https://v2.alapi.cn
          predicates:
            - Path=/api/interface/getRandomWords
          filters:
            - SetPath=/api/soul?format=json&token=H3HVyW1yhW0cNQRL
dubbo:
  application:
    name: mufengapi-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://10.206.25.10:8091